#!/bin/bash

REQUIRED_PKG="g++ cmake libsdl2-2.0 libsdl2-dev libsdl2-image-dev"
PKG_OK=$(dpkg-query -W --showformat='${Status}\n' $REQUIRED_PKG|grep "install ok installed")
echo Checking for $REQUIRED_PKG: $PKG_OK

if [ "" = "$PKG_OK" ]; then
  echo "No $REQUIRED_PKG. Setting up $REQUIRED_PKG."
  sudo apt-get --yes install $REQUIRED_PKG
fi

DIRS="res src bin bin/debug bin/release include"
	 
if ! [ mkdir -p "$DIRS" ];
then
	echo "ERROR: Directories already exist !"
	exit 1
	else
	mkdir res src bin bin/debug bin/release include
	echo "Done creating directories"
	fi
fi
